name: vtun-embedded
base: core22
version: '3.1.0'
license: GPL-2.0-or-later
title: simple network tunneling service
summary: vtun-embedded, fork of vtun, simple network tunneling service
description: Simple network tunneling service compatible with vtun. Fork of vtun.

contact:
  - sigsegv@radiotube.org

issues:
  - https://github.com/leakingmemory/vtun-embedded/issues
website:
  - https://github.com/leakingmemory/vtun-embedded

source-code:
  - https://github.com/leakingmemory/vtun-embedded.git

grade: stable
confinement: strict

apps:
  vtunemd:
    command: bin/vtunemd
    plugs:
      - network
      - network-bind
      - network-control
      - system-observe
      - process-control

parts:
  vtunemd:
    plugin: make
    source: .
    override-build: |
      patch -p1 -N < flatpak/patch-nonroot.patch
      autoreconf -i
      ./configure --prefix=/
      make
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
    build-packages:
      - gcc
      - make
      - bison
      - flex
      - libssl-dev
      - zlib1g-dev
      - liblzo2-dev
      - libbsd-dev
      - autoconf
      - build-essential
      - patch
    stage-packages:
      - net-tools
      - iproute2